server:
  port: ${acp_server_port:9090}
  undertow:
    threads:
      worker: 1000
logging:
  file:
    path: ${acp_log_path:logs}/${spring.application.name}
    name: ${logging.file.path}/${spring.application.name}.log
  pattern:
    file: '[%date{yyyy-MM-dd HH:mm:ss.SSS}] [ %-5level] [%thread] %logger{96} [%X{lineno}] - %msg%n'
  logback:
    rollingpolicy:
      max-file-size: 100MB
      max-history: 30
info:
  version: 1.0.0
  app-name: ${spring.application.name}
  api-document: /doc.html
  tags:
    environment: ${spring.profiles.active}
  build:
    author: zhangbin
    active: ${spring.profiles.active}
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  info:
    java:
      enabled: true
    env:
      enabled: true
spring:
  profiles:
    active: ${acp_profile_active:dev}
  application:
    name: acp-admin-standalone
  thymeleaf:
    cache: false
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  # ===============================
  # = JPA / HIBERNATE
  # ===============================
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
  # ===============================
  # = DATA SOURCE
  # ===============================
  datasource:
    hikari:
      maximum-pool-size: 5
      minimum-idle: 5
      pool-name: acp-admin-standalone
      max-lifetime: 480000
      idle-timeout: 300000
      connection-timeout: 10000
      read-only: false
knife4j:
  enable: true
# ===============================
# = ACP Config
# ===============================
acp:
  swagger:
    enabled: true