acp:
  controller-log:
    enabled: true
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/acp-admin-standalone?characterEncoding=utf-8&autoReconnect=true&failOverReadOnly=false&serverTimezone=UTC&useSSL=false
    username: root
    password: test
    driver-class-name: com.mysql.cj.jdbc.Driver